services:
  frontend-app:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile.dev

    image: devshittu/mediaapp:frontend-app-latest
    # Set environment variables directly in the docker-compose file
    environment:
      # ENV_VARIABLE: ${ENV_VARIABLE}
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      - NODE_ENV=development
      - VIRTUAL_HOST=app.staging.gong.ng,www.app.staging.gong.ng
      - LETSENCRYPT_HOST=app.staging.gong.ng,www.app.staging.gong.ng
      - LETSENCRYPT_EMAIL=devshittu@gmail.com

    # Set envrionment variables based on the .env file
    env_file:
      - .env.docker-compose

    restart: always
    ports:
      - 3000:3000
    networks:
      - my_media_network
    # depends_on:
    #   - web-app

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_media_network:
    external: true
# volumes:
# frontend-node-modules:
# Path: docker-compose.staging.yml
# /Users/mshittu/programming-projects/javascript/react/new-next/docker-compose.staging.yml
